[package]
name = "tracker_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
serde_json.workspace = true
once_cell = "1.19.0"
rayon = "1.10.0"
tokio = { workspace = true, features = ["full"] }
chrono.workspace = true

[features]
default = ["local_creds"]
local_creds = []
