[package]
name = "tracker_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[features]
default = ["local_creds"]
local_creds = []
