[workspace]

members = [
    "tracker_analyzer",
    "tracker_console",
]

[workspace.dependencies]
aws-config = "1.5.1"
aws-sdk-dynamodb = "1.34.0"
tokio = { version = "1.38.0", features = ["full"] }
