[workspace]
resolver = "2"

members = [
    "tracker_analyzer",
    "tracker_api",
    "tracker_console",
]

[workspace.dependencies]
aws-config = "1.5.1"
aws-sdk-dynamodb = "1.34.0"
tokio = { version = "1.38.0", features = ["full"] }
serde_json = "1.0.117"
chrono = "0.4.38"
rayon = "1.10.0"

